// access_token 
const ACCESS_SECOND = 60;
const ACCESS_MINUTE = 15;
const ACCESS_HOUR = 60;

// refresh_token
const REFRESH_SECOND = 60;
const REFRESH_MINUTE = 60;
const REFRESH_HOUR = 60;
const REFRESH_DAY = 14;

module.exports = {
  ACCESS_TOKEN_EXPIRE : ACCESS_SECOND * ACCESS_MINUTE,
  REFRESH_TOKEN_EXPIRE : REFRESH_SECOND * REFRESH_MINUTE,

  CHECK_SUCCESS: 101,
	CHECK_EXPIRED: 102,
	CHECK_FAILED: 103,
	
	REFRESH_SUCCESS: 201,
	REFRESH_EXPIRED: 202,
	REFRESH_ACCESS_TOKEN_ERROR: 203,
};
